from selenium.webdriver.common.by import By


class LoginPageLocators:
    USER_NAME = (By.CSS_SELECTOR, "[name='UserName']")
    PASS_WORD = (By.CSS_SELECTOR, "[name='Password']")
    LOGIN_BUTTON = (By.CSS_SELECTOR, "[class='btn btn-blue btn-upload']")
    LOGOUT_BUTTON = (By.CSS_SELECTOR, ".logoutLink")


class MainPageLocators:
    MANAGE_SHOWS_LINK = (By.XPATH, "//*[contains (@class,'link__title') and contains (text(), 'Manage Shows')]")
    CREATE_NEW_SHOW_LINK = (By.XPATH, "//div[contains (text(), 'Create New Show')]")


class ManageShowLocators:
    CARDS_LIST = (By.CSS_SELECTOR, "[class='show shows__item']")
    MANAGE_SHOWS_TITLE = (By.XPATH, "//*[contains (@class,'header__title') and contains (text(), 'Manage Shows')]")
    SEARCH_FIELD = (By.XPATH, "//div[@class='search__wrapper']")
    SEARCH_FIELD_INPUT = (By.XPATH, "//div[@class='search__wrapper']/input")
    APPLY_BTN = (By.XPATH, "//span[contains (text(), 'Apply')]")
    STATUS = (By.XPATH, "//div[@class='status__label']")
    ACTIVE_BTN = (By.XPATH, "//div[@class='header__btn header__btn_apply']/preceding::div[@class='header__control'][last()-4]/div/button/child::span[@class='v-filter__caret']")
    ACTIVE_CHX = (By.XPATH, "//label[contains (text(), 'Active')]")
    INACTIVE_CHX = (By.XPATH, "//label[contains (text(), 'Inactive')]")
    DELIVERED_CHX = (By.XPATH, "//label[contains (text(), 'Delivered')]")
    EDIT_SHOW_TITLE = (By.XPATH, "//div[@class='header__title']/span[contains (text(), 'Edit Show')]")
    SHOW_STATS_TAB = (By.XPATH, "//li[@class = 'VTab__btn VTab__btn_showStats VTab__btn_active']/div[@class='tabTitle']/span[contains (text(),'Show Stats')]")
    SHOW_ONES_TITLE = (By.XPATH, "//*[contains (@class,'main-title') and contains (text(), 'Show Ones')]")
    FINANCIALS_TITLE = (By.XPATH, "//*[contains (@class,'main-subtitle') and contains (text(), 'Financials')]")
    CREATE_NEW_SHOW_BTN = (By.XPATH, "//*[contains (@class,'VButton__text') and contains (text(), 'Create New Show')]")
    SHOW_INPUT_TAB = (By.XPATH, "//div[@class='tabTitle']/span[contains (text(), 'Show Inputs')]")
    AVG_ARTIST_DAY_RATES = (By.XPATH, "//div[@class='tabTitle']/span[contains (text(), 'Avg Artist Day Rates')]")
    OUTSOURCE_PATES = (By.XPATH, "//div[@class='tabTitle']/span[contains (text(), 'Outsource Rates')]")
    BID_WEEKS = (By.XPATH, "//*[contains (@class,'tab-title') and contains (text(), 'Bid Weeks')]")
    CONTRACT_VALUE = (By.XPATH, "//*[contains (@class,'tab-title') and contains (text(), 'Contract Value')]")
    INDIRECT_COSTS = (By.XPATH, "//*[contains (@class,'tab-title') and contains (text(), 'Indirect Cost')]")
    INTERNAL_BID = (By.XPATH, "//*[contains (@class,'tab-title') and contains (text(), 'Internal Bid')]")
    BID_WEEKS_UPLOAD = (By.XPATH, "//div[@class ='uploader']")
    SHOW_CODE_FIELD =(By.XPATH, "//div[contains (text(), 'Code')]/following-sibling::div[@class ='input-group__input']/descendant::span")
    DELETE_BTN = (By.XPATH, "//div[@class='VButton-block footer__btn_delete VButton-theme_red']/button")
    YES_DELETE_BTN = (By.XPATH, "//span[contains (@class,'VButton__text') and contains (text(), 'Yes, Delete')]")
    SHOW_CARDS_LIST = (By.XPATH, "//div[@class='vue-recycle-scroller__item-wrapper']/div[@style!='transform: translateY(-9999px);']/descendant::div[@class='show shows__item']")
    SHOW_CODE_IN_ONES = (By.XPATH, "//div[@class ='Vheader__show']/descendant::div[@class='btn__overflow']")
    SHOW_CODE_AND_NAME = (By.XPATH, "//div[@class='info__title']")
    BID_WEEKS_EMPTY = (By.XPATH, "//div[@class='empty-tab']")
    SHOW_CODE_AND_NAME_AFTER_SEARCH = (By.XPATH, "//div[@class='vue-recycle-scroller__item-wrapper']/div[@style!='transform: translateY(-9999px);']/descendant::div[@class='show shows__item']/descendant::div[@class='info__title']")

class CreateNewShowLocators:
    CREATE_SHOW_TITLE = (By.XPATH, "//div[@class='header__title']/span[contains (text(), 'Create Show')]")
    INPUT = (By.XPATH, "//div[@class ='VInputFake__input']/input")
    SHOW_CODE_MUST_BE_UNIQ_MESSAGE = (By.XPATH, "//div[contains (@class,'toast-message') and contains (text(), 'Show code is mandatory and must be uniq')]")
    SHOW_COLOR_ARROW = (By.XPATH, "//div[contains (@class,'toggle__color')]")
    COLOR_INPUT = (By.XPATH, "//div[@class='tab__field']//descendant::input")
    OK_BUTTON = (By.XPATH, "//*[contains (@class,'VButton__text') and contains (text(), 'Ok')]")
    BACK_BUTTON = (By.XPATH, "//div[@class='buttons__back_icon']")
    ACTUAL_CATEGORY_CHEVRON= (By.XPATH, "//div[contains (text(), 'Actual Category')]/following-sibling::div/*[@class='svg-inline--fa fa-chevron-down fa-w-14']")
    ACTUAL_CATEGORY_DROPDOWN = (By.XPATH, "//a[contains (text(), 'Theatrical')]")
    PLANNING_CATEGORY_CHEVRON = (By.XPATH, "//div[contains (text(), 'Planning Category')]/following-sibling::div/*[@class='svg-inline--fa fa-chevron-down fa-w-14']")
    PLANNING_CATEGORY_DROPDOWN = (By.XPATH, "//a[contains (text(), 'Theatrical')]")
    AMOUNT_OF_ASSETS_FIELD = (By.XPATH,"//div[contains (text(), 'Amount of Assets')]/following-sibling::div[@class ='input-group__input' ]/descendant::span")
    AMOUNT_OF_SHOTS_FIELD = (By.XPATH,"//div[contains (text(), 'Amount of Shots')]/following-sibling::div[@class ='input-group__input' ]/descendant::span")
    END_DATE_FIELD = (By.XPATH,"//div[contains (text(), 'End Date')]/following-sibling::div[@class ='input-group__input input-group__input_date-picker']")
    TODAY_FROM_CALENDAR = (By.XPATH, "//tr[@class='mx-date-row']/td[@class = 'cell today']")
    CONFIRM_BTN = (By.XPATH, "//button[@class = 'mx-btn mx-datepicker-btn-confirm']")
    START_DAY_CALENDAR = (By.XPATH, "//div[contains (text(), 'Start Date')]/following-sibling::div[@class ='input-group__input input-group__input_date-picker']")
    ARTIST_FIELD = (By.XPATH, "//div[contains (text(), 'Key Artist %')]/parent::div/preceding-sibling::div/div[contains (text(), 'Artist %')]/following-sibling::div")
    KEY_ARTIST_FIELD = (By.XPATH, "//div[contains (text(), 'Key Artist %')]/following-sibling::div/div[@class='VInputFake VInputFake_number VInputFake_default-new']")
    LEAD_FIELD = (By.XPATH, "//div[contains (text(), 'Lead %')]/following-sibling::div/div[@class='VInputFake VInputFake_number VInputFake_default-new']")
    SUPERVISOR_FIELD = (By.XPATH, "//div[contains (text(), 'Supervisor %')]/following-sibling::div/div[@class='VInputFake VInputFake_number VInputFake_default-new']")
    SHOW_CURRENCY_CHEVRON = (By.XPATH, "//div[contains (text(), 'Show Currency')]/following-sibling::div/*[@class='svg-inline--fa fa-chevron-down fa-w-14']")
    SHOW_CURRENCY_DROPDOWN = (By.XPATH, "//ul[@class='dropdown-menu']/li/a[contains( text(),'CAD ($)')]")
    AWARDS_EST_FIELD = (By.XPATH, "//div[contains (text(), 'Awards Est')]/following-sibling::div/div[@class='VInputFake VInputFake_number VInputFake_default-new']")
    PRIMARY_CHEVRON = (By.XPATH, "//div[contains (text(), 'Primary')]/following-sibling::div/*[@class='svg-inline--fa fa-chevron-down fa-w-14']")
    PRIMARY_DROPDOWN = (By.XPATH, "//ul[@class='dropdown-menu']/li/a[contains( text(),'Adelaide (MPC)')]")
    ADELAIDE_FIELD = (By.XPATH, "//div[contains (text(), 'Adelaide')]/following-sibling::div[@class ='input-group__input input-group__input_date-picker']")
    DATE_ACTIVE = (By.XPATH, "//tr[@class='mx-date-row']/td[@class = 'cell']")
    PRIMARY_PRODUCER_CHEVRON = (By.XPATH, "//div[contains (text(), 'Primary Producer')]/following-sibling::div/*[@class='svg-inline--fa fa-chevron-down fa-w-14']")
    PRIMARY_PRODUCER_DROPDOWN = (By.XPATH, "//ul[@class='dropdown-menu']/li[@class='VSelect__search search']/following-sibling::li/a[contains(text(),'aaron@mrxfx.com')]")
    CREATE_SHOW_BTN = (By.XPATH, "//button[@class='btn VButton']/span[contains (text(), 'Create show')]")